import express from 'express'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import db from '../db/database.js'
import { scanContent } from '../services/contentScanner.js'
import { extractRawText, storeExtractedContent } from '../services/pdfParser.js'
import { runCode, runShellCommand } from '../services/codeSandbox.js'
import { getChallenges } from '../services/challengeGenerator.js'

const router = express.Router()

router.use((req, res, next) => {
  console.log(`[Content Router] ${req.method} ${req.path}`);
  next();
});

router.get('/exercises/:courseSlug/:exerciseType', (req, res, next) => {
  try {
    const { courseSlug, exerciseType } = req.params;
    const validTypes = ['mcq', 'flashcards', 'ftb', 'matching', 'bossbattle', 'challenge'];
    if (!validTypes.includes(exerciseType)) {
      return res.status(400).json({ error: "Invalid exercise type" });
    }

    const course = db.prepare('SELECT track_id FROM courses WHERE slug = ?').get(courseSlug);
    if (!course) return res.status(404).json({ error: 'Course not found' });

    const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id);
    if (!track) return res.status(404).json({ error: 'Track not found' });

    const contentFolder = process.env.CONTENT_FOLDER 
      ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
          ? process.env.CONTENT_FOLDER 
          : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
      : DEFAULT_CONTENT_FOLDER;

    const exercisePath = path.join(contentFolder, 'tracks', track.slug, courseSlug, 'exercises', `${exerciseType}.json`);

    if (!fs.existsSync(exercisePath)) {
      return res.status(404).json({ error: "No exercises found for this type" });
    }

    const fileData = fs.readFileSync(exercisePath, 'utf-8');
    const data = JSON.parse(fileData);
    let items = [];

    // Handle both raw arrays and wrapper objects
    if (Array.isArray(data)) {
      items = data;
    } else {
      if (exerciseType === 'mcq') items = data.questions || [];
      else if (exerciseType === 'flashcards') items = data.cards || [];
      else if (exerciseType === 'ftb') items = data.exercises || [];
      else if (exerciseType === 'matching') items = data.rounds || [];
      else if (exerciseType === 'bossbattle') items = data.questions || [];
      else if (exerciseType === 'challenge') items = data.challenges || [];
    }

    // Schema mapping for compatibility with frontend components
    if (exerciseType === 'mcq' || exerciseType === 'bossbattle') {
      items = items.map(q => ({
        ...q,
        option_a: q.options?.a,
        option_b: q.options?.b,
        option_c: q.options?.c,
        option_d: q.options?.d
      }));
    }

    if (exerciseType === 'ftb') {
      items = items.map(ex => {
        let code = ex.code_template || "";
        const answers = (ex.blanks || []).map(b => b.answer);
        // Replace _____ with [[0]], [[1]], etc.
        let count = 0;
        while (code.includes('_____')) {
          code = code.replace('_____', `[[${count}]]`);
          count++;
        }
        return {
          ...ex,
          description: ex.task_description || ex.description,
          code,
          answers
        };
      });
    }

    // Shuffle and count
    if (exerciseType === 'mcq' && req.query.count) {
      const count = parseInt(req.query.count, 10);
      if (!isNaN(count)) {
        for (let i = items.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [items[i], items[j]] = [items[j], items[i]];
        }
        items = items.slice(0, count);
      }
    }

    if (exerciseType === 'flashcards' && req.query.shuffle === 'true') {
      for (let i = items.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [items[i], items[j]] = [items[j], items[i]];
      }
    }

    res.json(items);
  } catch (err) {
    next(err);
  }
});

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const DEFAULT_CONTENT_FOLDER = path.resolve(__dirname, '../../content')

router.post('/scan', (req, res, next) => {
  try {
    const summary = scanContent()
    res.status(200).json(summary)
  } catch (err) {
    next(err)
  }
})

/**
 * Returns raw text extracted from the course PDF.
 * Called by Gemini CLI subagent.
 */
router.get('/extract-text/:courseSlug', (req, res, next) => {
  try {
    const { courseSlug } = req.params
    const data = extractRawText(courseSlug)
    res.json(data)
  } catch (err) {
    next(err)
  }
})

/**
 * Stores concepts and quiz questions generated by the AI.
 * Called by Gemini CLI subagent.
 */
router.post('/store/:courseSlug', (req, res, next) => {
  try {
    const { courseSlug } = req.params
    const result = storeExtractedContent(courseSlug, req.body)
    res.json(result)
  } catch (err) {
    next(err)
  }
})

/**
 * Deprecated endpoint. Direct parsing removed.
 */
router.post('/parse/:courseSlug', (req, res) => {
  res.status(410).json({ 
    error: "Direct parsing removed. Use Gemini CLI extract-course command instead." 
  })
})

router.get('/pdf/:courseSlug', (req, res, next) => {
  try {
    const { courseSlug } = req.params
    const type = req.query.type || 'slides'
    
    const course = db.prepare('SELECT id, track_id, has_pdf, has_glossary FROM courses WHERE slug = ?').get(courseSlug)
    if (!course) return res.status(404).json({ error: 'Course not found' })

    if (type === 'slides' && !course.has_pdf) return res.status(404).json({ error: 'Slides PDF not found' })
    if (type === 'glossary' && !course.has_glossary) return res.status(404).json({ error: 'Glossary PDF not found' })

    const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id)
    if (!track) return res.status(404).json({ error: 'Track not found' })

    const contentFolder = process.env.CONTENT_FOLDER 
      ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
          ? process.env.CONTENT_FOLDER 
          : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
      : DEFAULT_CONTENT_FOLDER
      
    const fileName = type === 'slides' ? `${courseSlug}.pdf` : `${courseSlug}-glossary.pdf`
    const absolutePath = path.join(contentFolder, 'tracks', track.slug, courseSlug, fileName)

    if (!fs.existsSync(absolutePath)) {
      return res.status(404).json({ error: 'File not found on disk' })
    }

    res.contentType('application/pdf')
    res.sendFile(absolutePath)
  } catch (err) {
    next(err)
  }
})

router.get('/datasets/:courseSlug', (req, res, next) => {
  try {
    const { courseSlug } = req.params
    const course = db.prepare('SELECT track_id FROM courses WHERE slug = ?').get(courseSlug)
    if (!course) return res.status(404).json({ error: 'Course not found' })

    const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id)
    if (!track) return res.status(404).json({ error: 'Track not found' })

    const contentFolder = process.env.CONTENT_FOLDER 
      ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
          ? process.env.CONTENT_FOLDER 
          : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
      : DEFAULT_CONTENT_FOLDER

    const datasetsPath = path.join(contentFolder, 'tracks', track.slug, courseSlug, 'datasets')

    if (!fs.existsSync(datasetsPath) || !fs.statSync(datasetsPath).isDirectory()) {
      return res.status(200).json([])
    }

    const files = fs.readdirSync(datasetsPath)
    const validExtensions = ['.csv', '.sql', '.pkl', '.p', '.json', '.xlsx']
    
    const datasets = files
      .filter(file => !file.startsWith('.') && validExtensions.includes(path.extname(file).toLowerCase()))
      .map(file => {
        const stats = fs.statSync(path.join(datasetsPath, file))
        return {
          name: file,
          extension: path.extname(file),
          size_kb: Math.round(stats.size / 1024)
        }
      })

    res.status(200).json(datasets)
  } catch (err) {
    next(err)
  }
})

router.get('/challenges/:courseSlug', (req, res, next) => {
  try {
    const { courseSlug } = req.params
    
    const course = db.prepare('SELECT id, track_id FROM courses WHERE slug = ?').get(courseSlug);
    if (course) {
      const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id);
      if (track) {
        const contentFolder = process.env.CONTENT_FOLDER 
          ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
              ? process.env.CONTENT_FOLDER 
              : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
          : DEFAULT_CONTENT_FOLDER;

        const exercisePath = path.join(contentFolder, 'tracks', track.slug, courseSlug, 'exercises', 'challenge.json');

        if (fs.existsSync(exercisePath)) {
          const fileData = fs.readFileSync(exercisePath, 'utf-8');
          const data = JSON.parse(fileData);
          const items = Array.isArray(data) ? data : (data.challenges || []);
          if (items.length > 0) {
            return res.json(items);
          }
        }
      }
    }

    const challenges = getChallenges(courseSlug)
    if (!challenges || challenges.length === 0) {
      return res.status(404).json({ error: 'No datasets available for this course' })
    }
    
    res.json(challenges)
  } catch (err) {
    next(err)
  }
})

router.post('/run-code', (req, res, next) => {
  try {
    const { code, courseSlug, datasetFile } = req.body
    
    const course = db.prepare('SELECT track_id FROM courses WHERE slug = ?').get(courseSlug)
    if (!course) return res.status(404).json({ error: 'Course not found' })

    const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id)
    if (!track) return res.status(404).json({ error: 'Track not found' })

    const contentFolder = process.env.CONTENT_FOLDER 
      ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
          ? process.env.CONTENT_FOLDER 
          : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
      : DEFAULT_CONTENT_FOLDER

    const datasetPath = path.join(contentFolder, 'tracks', track.slug, courseSlug, 'datasets', datasetFile)
    
    if (!fs.existsSync(datasetPath)) {
      return res.status(404).json({ error: 'Dataset file not found' })
    }

    const result = runCode(code, [datasetPath])
    
    if (result.error && result.error.includes('ETIMEDOUT')) {
      result.error = "Code timed out after 10 seconds. Check for infinite loops."
    }

    res.json(result)
  } catch (err) {
    next(err)
  }
})

router.post('/run-shell', (req, res, next) => {
  try {
    const { courseSlug, datasetFile, history, command } = req.body
    
    const course = db.prepare('SELECT track_id FROM courses WHERE slug = ?').get(courseSlug)
    if (!course) return res.status(404).json({ error: 'Course not found' })

    const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id)
    if (!track) return res.status(404).json({ error: 'Track not found' })

    const contentFolder = process.env.CONTENT_FOLDER 
      ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
          ? process.env.CONTENT_FOLDER 
          : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
      : DEFAULT_CONTENT_FOLDER

    const datasetPath = path.join(contentFolder, 'tracks', track.slug, courseSlug, 'datasets', datasetFile)
    
    if (!fs.existsSync(datasetPath)) {
      return res.status(404).json({ error: 'Dataset file not found' })
    }

    const historyCode = (history || []).join('\n')
    const result = runShellCommand(historyCode, command, [datasetPath])
    
    res.json(result)
  } catch (err) {
    next(err)
  }
})

router.post('/submit-challenge', (req, res, next) => {
  try {
    const { code, courseSlug, challengeId, datasetFile, expectedOutputCode, solutionCode, solution_code } = req.body
    const expectedCode = expectedOutputCode || solutionCode || solution_code
    console.log(`[submit-challenge] Request received for ${courseSlug} - ${datasetFile}`)
    
    const course = db.prepare('SELECT id, track_id FROM courses WHERE slug = ?').get(courseSlug)
    if (!course) return res.status(404).json({ error: 'Course not found' })

    const track = db.prepare('SELECT slug FROM tracks WHERE id = ?').get(course.track_id)
    if (!track) return res.status(404).json({ error: 'Track not found' })

    const contentFolder = process.env.CONTENT_FOLDER 
      ? (path.isAbsolute(process.env.CONTENT_FOLDER) 
          ? process.env.CONTENT_FOLDER 
          : path.resolve(__dirname, '../', process.env.CONTENT_FOLDER))
      : DEFAULT_CONTENT_FOLDER

    const datasetPath = path.join(contentFolder, 'tracks', track.slug, courseSlug, 'datasets', datasetFile)
    console.log(`[submit-challenge] datasetPath: ${datasetPath}`)
    
    if (!fs.existsSync(datasetPath)) {
      console.log(`[submit-challenge] datasetPath does NOT exist!`)
      return res.status(404).json({ error: 'Dataset file not found' })
    }

    console.log(`[submit-challenge] Running user code...`)
    const userResult = runCode(code, [datasetPath])
    console.log(`[submit-challenge] User result:`, userResult)
    
    console.log(`[submit-challenge] Running expected code...`)
    const expectedResult = runCode(expectedCode, [datasetPath])
    console.log(`[submit-challenge] Expected result:`, expectedResult)
    
    if (!expectedResult.success) {
      return res.status(500).json({ error: 'Expected solution failed to run: ' + expectedResult.error })
    }

    if (!userResult.success) {
      return res.status(400).json({ error: userResult.error })
    }

    function normalizeOutput(output) {
      return output
        .trim()
        .split('\n')
        .map(line => line.trimEnd())
        .filter(line => line !== 'None')
        .filter(line => line !== '')
        .join('\n')
    }

    const passed = normalizeOutput(userResult.output) === normalizeOutput(expectedResult.output)
    const score = passed ? 100 : 0
    
    // Record attempt
    db.prepare(`
      INSERT INTO exercise_attempts (exercise_type, course_id, question_id, score, time_taken_secs, was_correct)
      VALUES (?, ?, ?, ?, ?, ?)
    `).run('dataset', course.id, null, score / 100, 0, passed ? 1 : 0)

    res.json({
      passed,
      score,
      user_output: normalizeOutput(userResult.output),
      expected_output: normalizeOutput(expectedResult.output),
      feedback: passed 
        ? 'Correct! Your output matches perfectly.'
        : 'Not quite. Compare your output with the expected output below.'
    })
  } catch (err) {
    next(err)
  }
})

export default router
